// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA80ga-DQ5WiFUrNSJGxEiRqERXgTkz4lk',
    appId: '1:1095160567129:web:a33515e10309dc49c6a848',
    messagingSenderId: '1095160567129',
    projectId: 'mark-it-down-76d9d',
    authDomain: 'mark-it-down-76d9d.firebaseapp.com',
    storageBucket: 'mark-it-down-76d9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9EOddQTxl2G3LwGcZEPTu1Io1TMh7eNA',
    appId: '1:1095160567129:android:9e04f866a0e2b886c6a848',
    messagingSenderId: '1095160567129',
    projectId: 'mark-it-down-76d9d',
    storageBucket: 'mark-it-down-76d9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ_FbaSwnJCHDqZiFnN1Y_lsmlo7ABLqs',
    appId: '1:1095160567129:ios:3245bd79d9d7d284c6a848',
    messagingSenderId: '1095160567129',
    projectId: 'mark-it-down-76d9d',
    storageBucket: 'mark-it-down-76d9d.firebasestorage.app',
    iosBundleId: 'com.example.markItDownV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ_FbaSwnJCHDqZiFnN1Y_lsmlo7ABLqs',
    appId: '1:1095160567129:ios:3245bd79d9d7d284c6a848',
    messagingSenderId: '1095160567129',
    projectId: 'mark-it-down-76d9d',
    storageBucket: 'mark-it-down-76d9d.firebasestorage.app',
    iosBundleId: 'com.example.markItDownV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA80ga-DQ5WiFUrNSJGxEiRqERXgTkz4lk',
    appId: '1:1095160567129:web:fb7033e9cbe20e81c6a848',
    messagingSenderId: '1095160567129',
    projectId: 'mark-it-down-76d9d',
    authDomain: 'mark-it-down-76d9d.firebaseapp.com',
    storageBucket: 'mark-it-down-76d9d.firebasestorage.app',
  );

}